"""add is_active to patients

Revision ID: 97b7f6b51be9
Revises: 1c67bf443f8f
Create Date: 2026-07-26 12:06:10.357506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b7f6b51be9'
down_revision: Union[str, Sequence[str], None] = '1c67bf443f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column(
        "patients",
        "is_active",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'is_active')
    # ### end Alembic commands ###
